const db = require('../db')

const seedBooks = () => db.Promise.map([
  {'title': 'Friday', 'author': 'Robert Heinlein', 'publicationDate': '1982', 'genre' : 'cassette-punk', summary: 'Friday is a secret courier. She is employed by a man known to her only as "Boss." Operating from and over a near-future Earth, in which North America has become Balkanized into dozens of independent states, where culture has become bizarrely vulgarized and chaos is the happy norm, she finds herself on shuttlecock assignment at Boss\' seemingly whimsical behest. From New Zealand to Canada, from one to another of the new states of America\'s disunion, she keeps her balance nimbly with quick, expeditious solutions to one calamity and scrape after another.'},
  {'title': 'Dawn','author': 'Octavia Butler', 'publicationDate': '1987', 'genre' : 'hard scifi', summary:"Lilith Iyapo has just lost her husband and son when atomic fire consumes Earth—the last stage of the planet’s final war. Hundreds of years later Lilith awakes, deep in the hold of a massive alien spacecraft piloted by the Oankali—who arrived just in time to save humanity from extinction. They have kept Lilith and other survivors asleep for centuries, as they learned whatever they could about Earth. Now it is time for Lilith to lead them back to her home world, but life among the Oankali on the newly resettled planet will be nothing like it was before.The Oankali survive by genetically merging with primitive civilizations—whether their new hosts like it or not. For the first time since the nuclear holocaust, Earth will be inhabited. Grass will grow, animals will run, and people will learn to survive the planet’s untamed wilderness. But their children will not be human. Not exactly.Featuring strong and compelling characters and exploring complex themes of gender and species, Octavia E. Butler presents a powerful, postapocalyptic interplanetary epic, as well as a ray of hope for humanity."},
  {'title': 'Dhalgren','author': 'Samuel Delany', 'publicationDate': '1975', 'genre' : 'Afrofuturism', summary: 'In Dhalgren, perhaps one of the most profound and bestselling science fiction novels of all time, Samuel R. Delany has produced a novel "to stand with the best American fiction of the 1970s" (Jonathan Lethem). Bellona is a city at the dead center of the United States. Something has happened there…. The population has fled. Madmen and criminals wander the streets. Strange portents appear in the cloud-covered sky. And into this disaster zone comes a young man–poet, lover, and adventurer–known only as the Kid. Tackling questions of race, gender, and sexuality, Dhalgren is a literary marvel and groundbreaking work of American magical realism.'},
  {'title': 'To Marry Medusa','author': 'Theodore Sturgeon', 'publicationDate' : '1958', 'genre' : 'speculative fiction', summary:'Up until one minute ago, Gurlick was merely a specimen of homo sapiens, and a substandard specimen at that. But now this craven, seething, barely literate drunk has ingested a spore that travelled light years before touching down on our planet. A spore that has in turn ingested Gurlick - turned him into a host for the Medusa, a hive mind so vast that it encompasses the life forms of a billion planets. A hive mind that is determined to ingest Earth as well.'},
  {'title': 'Bluebeard', 'author': 'Kurt Vonnegut', 'publicationDate': '1987', 'genre' : 'speculative fiction', summary: 'Broad humor and bitter irony collide in this fictional autobiography of Rabo Karabekian, who, at age seventy-one, wants to be left alone on his Long Island estate with the secret he has locked inside his potato barn. But then a voluptuous young widow badgers Rabo into telling his life story—and Vonnegut in turn tells us the plain, heart-hammering truth about man’s careless fancy to create or destroy what he loves.' },
  {'title': 'Binti', 'author': 'Nnedi Okorafor', 'publicationDate': '2015', 'genre' : 'Afrofuturism', summary:"Her name is Binti, and she is the first of the Himba people ever to be offered a place at Oomza University, the finest institution of higher learning in the galaxy. But to accept the offer will mean giving up her place in her family to travel between the stars among strangers who do not share her ways or respect her customs. Knowledge comes at a cost, one that Binti is willing to pay, but her journey will not be easy. The world she seeks to enter has long warred with the Meduse, an alien race that has become the stuff of nightmares. Oomza University has wronged the Meduse, and Binti's stellar travel will bring her within their deadly reach. If Binti hopes to survive the legacy of a war not of her making, she will need both the gifts of her people and the wisdom enshrined within the University, itself - but first she has to make it there, alive."},
  {'title': 'Frankenstein', 'author': 'Mary Shelley', 'publicationDate': '1818', 'genre' : 'hard scifi', summary: "Mary Shelley began writing Frankenstein when she was only eighteen. At once a Gothic thriller, a passionate romance, and a cautionary tale about the dangers of science, Frankenstein tells the story of committed science student Victor Frankenstein. Obsessed with discovering the cause of generation and life and bestowing animation upon lifeless matter, Frankenstein assembles a human being from stolen body parts but; upon bringing it to life, he recoils in horror at the creature's hideousness. Tormented by isolation and loneliness, the once-innocent creature turns to evil and unleashes a campaign of murderous revenge against his creator, Frankenstein. Frankenstein, an instant bestseller and an important ancestor of both the horror and science fiction genres, not only tells a terrifying story, but also raises profound, disturbing questions about the very nature of life and the place of humankind within the cosmos: What does it mean to be human? What responsibilities do we have to each other? How far can we go in tampering with Nature? In our age, filled with news of organ donation genetic engineering, and bio-terrorism, these questions are more relevant than ever." },
  {'title': 'Alien', 'author': 'Alan Dean Foster', 'publicationDate': '1979', 'genre' : 'cassette-punk', summary: "Based on the screenplay by Dan O'Bannon. The crew of the spaceship Nostromo wake from cryogenic sleep to distress signals from an unknown planet. One is attacked when they investigate a derelict alien craft. Safely on their way back to Sol, none foresee the real horror about to begin." },
  {'title':'Enchantress From The Stars', 'author': 'Sylvia Engdahl', 'publicationDate':'1970', 'genre':'speculative fiction', summary: "Elana is a member of a supremely advanced interstellar civilization, on a mission to the medieval planet Andrecia. To her shock, she becomes the key to a dangerous plan to turn back an invasion by an aggressive, space-faring \"Youngling\" species. How can she possibly help the Andrecians, who still believe in magic and superstition, without revealing her alien powers? Apprentice Medical Officer Jarel knows that the Imperial Exploration Corps doesn't consider the Andrecians to be human, and he has seen the atrocious treatment the natives get from his people. How can Jarel make a difference, when he alone regrets the destruction his people bring?Georyn, son of an Andrecian woodcutter, knows only that there is a dragon on the other side of the enchanted forest, and he is prepared to do whatever it takes to defeat it. To him, Elana is the Enchantress from the Stars who has come to test him, to prove his is worthy...."}
], book => db.model('books').create(book));


const seedReviews = () => db.Promise.map([
 {rating: 1, text: "too many machines",book_id:5},
 {rating: 1, text: "not enough machines ",book_id:1},
 {rating: 5, text: "the best!",book_id:2},
 {rating: 2, text: "waste of money",book_id:3},
 {rating: 3, text: "should have been more robots",book_id:4},
 {rating: 3, text: "should be better",book_id:6},
 {rating: 4, text: "blew my mind",book_id:7},
 {rating: 4, text: "just the right amount of robots",book_id:1}
 ], review => db.model('reviews').create(review));

 db.didSync
   .then(() => db.sync({force: true}))
   .then(seedBooks)
   .then(books => console.log(`Seeded ${books.length} books OK`))
   .then(seedReviews)
   .then(reviews => console.log(`Seeded ${reviews.length} reviews OK`))
   .catch(error => console.error(error))
   .finally(() => db.close())





